# Generated by Django 4.0.2 on 2022-04-02 19:12

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaneh',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default=(35.69939587605691, 51.337852477590786), max_length=63),
        ),
    ]
