# Generated by Django 4.0.2 on 2022-07-16 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTithe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('position', models.IntegerField(default=1, verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resaneh.incometithe', verbose_name='زیرشاخه')),
            ],
            options={
                'verbose_name': 'دهک درآمدی',
                'verbose_name_plural': 'دهک\u200cهای درآمدی',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('position', models.IntegerField(default=1, verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resaneh.gender', verbose_name='زیرشاخه')),
            ],
            options={
                'verbose_name': 'جنسیت',
                'verbose_name_plural': 'جنسیت\u200cها',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Ages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('position', models.IntegerField(default=1, verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resaneh.ages', verbose_name='زیرشاخه')),
            ],
            options={
                'verbose_name': 'رده\u200cی سنی',
                'verbose_name_plural': 'رده\u200cهای سنی',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.AddField(
            model_name='resaneh',
            name='ages',
            field=models.ManyToManyField(blank=True, related_name='resaneh', to='resaneh.Ages', verbose_name='رده\u200cی سنی'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='gender',
            field=models.ManyToManyField(blank=True, related_name='resaneh', to='resaneh.Gender', verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='incometithe',
            field=models.ManyToManyField(blank=True, related_name='resaneh', to='resaneh.IncomeTithe', verbose_name='دهک درآمدی'),
        ),
    ]
