# Generated by Django 4.0.2 on 2022-04-16 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان پایان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('resaneh', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resanehoffer', to='resaneh.resaneh', verbose_name='رسانه')),
            ],
            options={
                'verbose_name': 'پیشنهاد ویژه',
                'verbose_name_plural': 'پیشنهاد\u200cهای ویژه',
            },
        ),
    ]
