# Generated by Django 4.0.2 on 2022-06-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resaneh',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='رسانه\u200cی دیجیتال؟'),
        ),
    ]
