# Generated by Django 4.0.2 on 2022-06-10 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('resaneh', '0002_resaneh_is_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='cities.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='cities.country', verbose_name='کشور'),
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='cities.state', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='place',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='cities.zone', verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='resaneh',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='رسانه\u200cی دیجیتال'),
        ),
    ]
