# Generated by Django 4.0.2 on 2022-06-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0003_place_city_place_country_place_state_place_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='connectionID',
            field=models.CharField(blank=True, max_length=200, verbose_name='کد ارتباطی'),
        ),
    ]
