# Generated by Django 4.0.2 on 2022-04-17 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('resaneh', '0004_alter_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resaneh',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resaneh', to='cities.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resaneh', to='cities.country', verbose_name='کشور'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resaneh', to='cities.state', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resaneh', to='cities.zone', verbose_name='منطقه'),
        ),
    ]
