# Generated by Django 4.0.2 on 2022-06-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0004_place_address_resaneh_connectionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resaneh',
            name='androidVersion',
            field=models.CharField(blank=True, max_length=200, verbose_name='ورژن اندروید'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='is_Androidbox',
            field=models.BooleanField(default=False, verbose_name='سیستم\u200cعامل اندروید'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='number',
            field=models.CharField(blank=True, max_length=200, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='operatorNumber',
            field=models.CharField(blank=True, max_length=200, verbose_name='شماره\u200cی اپراتوری'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='tvModel',
            field=models.CharField(blank=True, max_length=200, verbose_name='مدل تلویزیون'),
        ),
        migrations.AddField(
            model_name='resaneh',
            name='tvSize',
            field=models.CharField(blank=True, max_length=200, verbose_name='ابعاد تلویزیون'),
        ),
    ]
