# Generated by Django 4.0.2 on 2022-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0005_resaneh_androidversion_resaneh_is_androidbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaneh',
            name='number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resaneh',
            name='operatorNumber',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
