# Generated by Django 4.0.2 on 2022-04-03 18:41

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0005_alter_resaneh_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('position', models.IntegerField(default=1, verbose_name='پوزیشن')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='categoryimages', verbose_name='تصویر')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resaneh.category', verbose_name='زیرشاخه')),
            ],
            options={
                'verbose_name': 'نوع رسانه',
                'verbose_name_plural': 'انواع رسانه',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.RemoveField(
            model_name='resaneh',
            name='mediatype',
        ),
        migrations.AlterField(
            model_name='resaneh',
            name='industry',
            field=models.ManyToManyField(related_name='resaneh', to='resaneh.Industry', verbose_name='صنعت'),
        ),
        migrations.AlterField(
            model_name='resaneh',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='35.69977923732504,411.33733749345987', max_length=63),
        ),
        migrations.AlterField(
            model_name='resaneh',
            name='showtype',
            field=models.ManyToManyField(blank=True, related_name='resaneh', to='resaneh.ShowType', verbose_name='نوع نمایش'),
        ),
        migrations.AlterField(
            model_name='resaneh',
            name='tag',
            field=models.ManyToManyField(related_name='resaneh', to='resaneh.Tag', verbose_name='تگ'),
        ),
        migrations.DeleteModel(
            name='MediaType',
        ),
        migrations.AddField(
            model_name='resaneh',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='resaneh', to='resaneh.Category', verbose_name='نوع رسانه'),
        ),
    ]
