# Generated by Django 4.0.2 on 2022-04-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0006_category_remove_resaneh_mediatype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تگ')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس تگ')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'گروه رسانه',
                'verbose_name_plural': 'گروه\u200cهای رسانه',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='resaneh',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resaneh', to='resaneh.group', verbose_name='گروه رسانه'),
        ),
    ]
