# Generated by Django 4.0.2 on 2022-06-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0006_alter_resaneh_number_alter_resaneh_operatornumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resaneh',
            name='number',
        ),
        migrations.AlterField(
            model_name='resaneh',
            name='operatorNumber',
            field=models.CharField(blank=True, max_length=200, verbose_name='تلفن اپراتور'),
        ),
    ]
