# Generated by Django 4.0.2 on 2022-04-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0007_group_resaneh_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='detail',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
