# Generated by Django 4.0.2 on 2022-06-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0007_remove_resaneh_number_alter_resaneh_operatornumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaneh',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت'),
        ),
    ]
