# Generated by Django 4.0.2 on 2022-04-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0008_group_detail_alter_group_slug_alter_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resaneh',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='قیمت'),
        ),
    ]
