# Generated by Django 4.0.2 on 2022-04-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0009_alter_resaneh_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('position', models.IntegerField(default=1, verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resaneh.structuretype', verbose_name='زیرشاخه')),
            ],
            options={
                'verbose_name': 'نوع سازه',
                'verbose_name_plural': 'انواع سازه',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.AddField(
            model_name='resaneh',
            name='structuretype',
            field=models.ManyToManyField(blank=True, related_name='resaneh', to='resaneh.StructureType', verbose_name='نوع سازه'),
        ),
    ]
