# Generated by Django 4.0.2 on 2022-04-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resaneh', '0011_remove_resaneh_structuretype_resaneh_structuretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('detail', models.TextField(blank=True, verbose_name='توضیحات')),
                ('pcode', models.CharField(blank=True, max_length=200, verbose_name='کد جایگاه')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'جایگاه',
                'verbose_name_plural': 'جایگاه\u200cها',
                'ordering': ['position'],
            },
        ),
        migrations.RemoveField(
            model_name='resaneh',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='resaneh',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resaneh', to='resaneh.place', verbose_name='گروه رسانه'),
        ),
    ]
