"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_URL = "account:login_register"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',



    'django_summernote',
    'comment',
    'crispy_forms',
    'location_field.apps.DefaultConfig',
    'django_filters',
    'hitcount',


    'home.apps.HomeConfig',
    'blog.apps.BlogConfig',
    'account.apps.AccountConfig',
    'resaneh.apps.ResanehConfig',
    'dashboard.apps.DashboardConfig',
    'cities.apps.CitiesConfig',
    'star_ratings',

    'VOD.apps.VodConfig',

    'rest_framework',
    'rest_framework.authtoken',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'blog.middleware.SaveIPAddressMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGES =[
    ('fa', 'Persian'),
    ('en', 'English')
]

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
#درحالت تست فعال بشه
STATIC_ROOT = BASE_DIR / 'static'

#درحالت دپلوی فعال بشه
# STATIC_ROOT = os.path.join(BASE_DIR, "static")

# STATICFILES_DIRS=[
#     os.path.join(BASE_DIR,'static')
# ]


MEDIA_URL = '/media/'

# درحالت تست فعال
MEDIA_ROOT = BASE_DIR / 'static/media'

# در حالت دپلوی فعال
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# برای سی پنل احمق
# MEDIA_ROOT = '/home2/irasanec/public_html/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'account.CustomUser'
AUTHENTICATION_BACKENDS = ["account.backends.PhoneAuthBackend"]

# for classified form
CRISPY_TEMPLATE_PACK = 'bootstrap4'


# PROFILE_APP_NAME = 'account'
# PROFILE_MODEL_NAME = 'Profile'

#google api for map
# LOCATION_FIELD = {
#     'provider.google.api': '//maps.google.com/maps/api/js?sensor=false',
#     'provider.google.api_key': 'AIzaSyCPteBr8Vs2bZVy5S4T3b6JQspG3QAMc9g',
#     'provider.google.api_libraries': '',
#     'provider.google.map.type': 'ROADMAP',
# }

LOCATION_FIELD = {
    'map.provider': 'openstreetmap',
    'map.zoom': 15,

    'search.provider': 'google',
    'search.suffix': '',
    }

STAR_RATINGS_STAR_HEIGHT = 16
# STAR_RATINGS_RANGE = 7
# STAR_RATINGS_ANNUNYMOUS = True
# STAR_RATINGS_RERATE = False
# STAR_RATINGS_STAR_SPRITE = os.path.join(BASE_DIR, 'img.jpg')


REST_FRAMEWORK = {
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ],
    #
    # 'DEFAULT_AUTHENTICATION_CLASSES': [
    #
    #     'rest_framework_simplejwt.authentication.JWTAuthentication',
    # ],
}
