# Generated by Django 4.0.2 on 2022-04-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_alter_blockeduser_id_alter_blockeduserhistory_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockeduser',
            options={'verbose_name': 'کاربر بلاک\u200cشده', 'verbose_name_plural': 'کاربران بلاک\u200cشده'},
        ),
        migrations.AlterModelOptions(
            name='blockeduserhistory',
            options={'verbose_name': 'تاریخچه کاربر بلاک\u200cشده', 'verbose_name_plural': 'تاریخچه کاربران بلاک\u200cشده'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted'], 'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='flag',
            options={'verbose_name': 'منتخب', 'verbose_name_plural': 'منتخب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': 'دنبال\u200cکننده', 'verbose_name_plural': 'دنبال\u200cکننده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'واکنش', 'verbose_name_plural': 'واکنش\u200cها'},
        ),
    ]
