# Generated by Django 4.0.2 on 2022-06-22 07:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resaneh', '0006_alter_resaneh_number_alter_resaneh_operatornumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='نام باکس آگهی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس باکس')),
                ('numberOfVideos', models.PositiveIntegerField(blank=True, verbose_name='تعداد ویدیوها')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'باکس',
                'verbose_name_plural': 'باکس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AdVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='نام ویدیو')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='نوع')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('video', models.FileField(blank=True, null=True, upload_to='advideos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'jpg'])], verbose_name='ویدیو')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advideo', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
            },
        ),
        migrations.CreateModel(
            name='AdVideoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='نام')),
                ('detail', models.TextField(blank=True, verbose_name='جزییات بیشتر')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advideolog', to='VOD.adbox', verbose_name='باکس')),
                ('resaneh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advideolog', to='resaneh.resaneh', verbose_name='رسانه')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advideolog', to='VOD.advideo', verbose_name='ویدیو')),
            ],
        ),
        migrations.CreateModel(
            name='AdVideoCounterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, verbose_name='جزییات بیشتر')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advideocounterlog', to='VOD.adbox', verbose_name='باکس')),
                ('resaneh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advideocounterlog', to='resaneh.resaneh', verbose_name='رسانه')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advideocounterlog', to='VOD.advideo', verbose_name='ویدیو')),
            ],
        ),
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('detail', models.TextField(blank=True, verbose_name='جزییات بیشتر')),
                ('startTime', models.TimeField(default=django.utils.timezone.now, verbose_name='ساعت شروع')),
                ('endTime', models.TimeField(default=django.utils.timezone.now, verbose_name='ساعت پایان')),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان شروع')),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان پایان')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adevent', to='VOD.adbox', verbose_name='باکس')),
                ('resaneh', models.ManyToManyField(blank=True, related_name='adevent', to='resaneh.Resaneh', verbose_name='رسانه')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
            },
        ),
        migrations.CreateModel(
            name='AdConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, verbose_name='جزییات بیشتر')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('resaneh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adconnectionlog', to='resaneh.resaneh', verbose_name='رسانه')),
            ],
        ),
        migrations.AddField(
            model_name='adbox',
            name='videos',
            field=models.ManyToManyField(related_name='adbox', to='VOD.AdVideo', verbose_name='ویدیوها'),
        ),
        migrations.CreateModel(
            name='AdApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='نام')),
                ('detail', models.TextField(blank=True, verbose_name='جزییات بیشتر')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('resaneh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adapplicationlog', to='resaneh.resaneh', verbose_name='رسانه')),
            ],
        ),
    ]
