# Generated by Django 4.0.2 on 2022-06-22 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VOD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adapplicationlog',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='adconnectionlog',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='advideocounterlog',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='advideolog',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
    ]
