# Generated by Django 4.0.2 on 2022-06-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VOD', '0002_alter_adapplicationlog_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdVideoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='نوع ویدیو')),
                ('detail', models.TextField(blank=True, verbose_name='جزییات بیشتر')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع ویدیو',
                'verbose_name_plural': 'انواع ویدیو',
            },
        ),
        migrations.AlterField(
            model_name='advideo',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advideo', to='VOD.advideotype', verbose_name='نوع'),
        ),
    ]
