# Generated by Django 4.0.2 on 2022-06-22 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VOD', '0004_advideo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advideo',
            name='condition',
            field=models.CharField(blank=True, choices=[('p', 'پیش\u200cنویس'), ('d', 'در انتظار بررسی'), ('y', 'تایید شده'), ('n', 'رد شده')], max_length=1, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='advideo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advideo', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
    ]
