# Generated by Django 4.0.2 on 2022-06-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VOD', '0005_advideo_condition_alter_advideo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adbox',
            name='slug',
        ),
    ]
