# Generated by Django 4.0.2 on 2022-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VOD', '0006_remove_adbox_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbox',
            name='order',
            field=models.CharField(blank=True, max_length=200, verbose_name='ترتیب نمایش فیلم\u200cها'),
        ),
    ]
