# Generated by Django 4.0.2 on 2022-06-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VOD', '0007_adbox_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbox',
            name='order',
            field=models.CharField(blank=True, help_text='اعداد را به انگلیسی وارد کنید و با - فاصله دهید.', max_length=200, verbose_name='ترتیب نمایش فیلم\u200cها'),
        ),
    ]
