# Generated by Django 4.0.2 on 2022-07-11 06:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(help_text='Enter 10 digits phone number', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='مقدار وارد شده صحیح نمی\u200cباشد', regex='^[0]{1}[9]{1}[0-9]{9}')], verbose_name='Phone Number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('logo', models.ImageField(default='profileimages/profi.png', null=True, upload_to='companyimages', verbose_name='لوگو')),
                ('sphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن ثابت')),
                ('mphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='نام\u200cخانوادگی')),
                ('role', models.CharField(blank=True, choices=[('k', 'رسانه\u200cخواه'), ('b', 'رسانه\u200cدار و رسانه\u200cخواه')], default='k', max_length=1, null=True, verbose_name='نقش')),
                ('position', models.CharField(blank=True, choices=[('c', 'کارمند'), ('m', 'مدیر')], default='c', max_length=1, null=True, verbose_name='جایگاه')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('pic', models.ImageField(default='profileimages/profi.png', null=True, upload_to='profileimages', verbose_name='تصویر')),
                ('sphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن ثابت')),
                ('mphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه')),
                ('status', models.BooleanField(default=False, verbose_name='درخواست رسانه\u200cدار شدن')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.company', verbose_name='شرکت')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب کاربری',
                'verbose_name_plural': 'حساب\u200cهای کاربری',
            },
        ),
    ]
