# Generated by Django 4.0.2 on 2022-07-16 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='profileimages/profi.png', null=True, upload_to='companyimages', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='profileimages/profi.png', null=True, upload_to='profileimages', verbose_name='تصویر'),
        ),
    ]
