# Generated by Django 4.0.2 on 2022-07-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_code_user_alter_company_logo_alter_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='پروفایل تکمیل شده؟'),
        ),
    ]
