# Generated by Django 4.0.2 on 2022-03-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(default='profileimages/profi.png', null=True, upload_to='profileimages'),
        ),
    ]
