# Generated by Django 4.0.2 on 2022-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mphone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sPhone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن ثابت'),
        ),
    ]
