# Generated by Django 4.0.2 on 2022-03-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_options_alter_profile_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('logo', models.ImageField(default='profileimages/profi.png', null=True, upload_to='companyimages', verbose_name='لوگو')),
                ('sPhone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن ثابت')),
                ('mphone', models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.company', verbose_name='شرکت'),
        ),
    ]
