# Generated by Django 4.0.2 on 2022-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_company_alter_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('c', 'کارمند'), ('m', 'مدیر')], default='c', max_length=1, null=True, verbose_name='جایگاه'),
        ),
    ]
