# Generated by Django 4.0.2 on 2022-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_profile_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام\u200cخانوادگی'),
        ),
    ]
