# Generated by Django 4.0.2 on 2022-04-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_name_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logo',
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='profileimages/profi.png', null=True, upload_to='profileimages', verbose_name='تصویر'),
        ),
    ]
