# Generated by Django 4.0.2 on 2022-04-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_profile_logo_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sPhone',
            new_name='sphone',
        ),
    ]
